main.out: ejercicio1.c options.h options.o
	gcc -g -o ejercicio1.out ejercicio1.c options.o -Wall -g -O0
options.o:
	gcc -g -c options.h options.c -Wall -g -O0
limpiar:
	rm ejercicio1.out options.o options.h.gch
