main.out: ejercicio4.c options.h options.o
	gcc -g -o ejercicio4.out ejercicio4.c options.o -Wall -g -O0
options.o:
	gcc -g -c options.h options.c -Wall -g -O0
limpiar:
	rm ejercicio4.out options.o options.h.gch
