main.out: ejercicio3.c options.h options.o
	gcc -g -o ejercicio3.out ejercicio3.c options.o -Wall -g -O0
options.o:
	gcc -g -c options.h options.c -Wall -g -O0
limpiar:
	rm ejercicio3.out options.o options.h.gch
